// import React from 'react';
// import Table from 'react-bootstrap/Table';
// import './BoardList.css'


// const BoardListWeb = () => {
  
//   return (
//     <div style={{display:'block',backgroundColor:'green'}}>
//       <Table style={{display:'block',margin:'100px'}}>
//         <thead style={{marginRight:'20px'}}>
//         <tr>
//             <th>번호</th>
//             <th>OS_ID</th>
//             <th>OS_NAME</th>
//             <th>Type</th>
//             <th>IP</th>
//             <th>계정수</th>
//             <th>관리자</th>
//             <th>생성일자</th>
//             <th>동기화일자</th>
//             <th>동기화여부</th>
//             <th>비고</th>
//         </tr>
//         </thead>
//         <tbody>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//         <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         <tr>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//             <td>1</td>
//         </tr>
//         </tbody>
//     </Table>
//     </div>
//   );
// };

// export default BoardListWeb;